CREATE TABLE IF NOT EXISTS EMPLOYEES (
    EMPLOYEE_NAME TEXT,
    EMPLOYEE_DEPARTMENT TEXT,
    SALARY REAL
);

INSERT INTO EMPLOYEES
VALUES
('CATON', 'HR', 21),
('MYINT', 'MARKETING', 28),
('EFENDI', 'IT', 25),
('LAL', 'FINANCE', 30);

SELECT * FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_DEPARTMENT) FROM EMPLOYEES;

SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT MAX(SALARY) FROM EMPLOYEES;