CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT,
    PRICE REAL
);

INSERT INTO PRODUCTS 
VALUES
('1', 'CHAI', '1', '1', '10 boxes x 20 bags', 18.00),
('2', 'CHANG', '1', '1', '24 - 12 oz bottles', 19.00),
('3', 'ANISEED SOUP', '1', '2', '12 - 550 ml bottles', 10.00),
('4', 'CHEF ANTON''S CAJUN SEASONING', '2', '2', '48 - 6 oz jars', 22.00),
('5', 'CHEF ANTON''S GUMBO MIX', '2', '2', '36 boxes', 21.35);

SELECT * FROM PRODUCTS;

SELECT COUNT(PRODUCT_ID) FROM PRODUCTS;

SELECT COUNT(DISTINCT SUPPLIER_ID) FROM PRODUCTS;

SELECT AVG(PRICE) FROM PRODUCTS;

SELECT MIN(PRICE) FROM PRODUCTS;
SELECT MAX(PRICE) FROM PRODUCTS;

SELECT SUM(PRICE) FROM PRODUCTS;

SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'C%';